In [1]:
import pandas as pd
import funcoes_exp as f
import yfinance as yf
from datetime import date

In [68]:
### BUSCA ATIVOS NO INVESTING

tickers = f.br_tickers()
df_stocks = f.br_stocks()

print(tickers)
df_stocks.head(3)

{'ABCB4': 'ABCB4.SA', 'AGRO3': 'AGRO3.SA', 'RAIL3': 'RAIL3.SA', 'ALPA3': 'ALPA3.SA', 'ALPA4': 'ALPA4.SA', 'ALSO3': 'ALSO3.SA', 'AMAR3': 'AMAR3.SA', 'ABEV3': 'ABEV3.SA', 'ADHM3': 'ADHM3.SA', 'ARZZ3': 'ARZZ3.SA', 'BBAS3': 'BBAS3.SA', 'BBDC3': 'BBDC3.SA', 'BBDC4': 'BBDC4.SA', 'BBRK3': 'BBRK3.SA', 'BEEF3': 'BEEF3.SA', 'BPHA3': 'BPHA3.SA', 'BPAN4': 'BPAN4.SA', 'BRAP3': 'BRAP3.SA', 'BRAP4': 'BRAP4.SA', 'BRFS3': 'BRFS3.SA', 'APER3': 'APER3.SA', 'BRKM3': 'BRKM3.SA', 'BRKM5': 'BRKM5.SA', 'BRML3': 'BRML3.SA', 'BRPR3': 'BRPR3.SA', 'BRSR6': 'BRSR6.SA', 'OIBR3': 'OIBR3.SA', 'OIBR4': 'OIBR4.SA', 'BTOW3': 'BTOW3.SA', 'B3SA3': 'B3SA3.SA', 'CAMB4': 'CAMB4.SA', 'CARD3': 'CARD3.SA', 'CCPR3': 'CCPR3.SA', 'CCRO3': 'CCRO3.SA', 'CEDO4': 'CEDO4.SA', 'CEED3': 'CEED3.SA', 'CESP6': 'CESP6.SA', 'CGAS5': 'CGAS5.SA', 'CGRA4': 'CGRA4.SA', 'CIEL3': 'CIEL3.SA', 'CMIG3': 'CMIG3.SA', 'CMIG4': 'CMIG4.SA', 'COCE5': 'COCE5.SA', 'CPFE3': 'CPFE3.SA', 'CPLE3': 'CPLE3.SA', 'CPLE6': 'CPLE6.SA', 'CRDE3': 'CRDE3.SA', 'CSAN3': 'CSAN3.SA', 'CSMG3': 'CSMG3.SA', 'CSNA3': 'CSNA3.SA', 'LIQO3': 'LIQO3.SA', 'CTNM4': 'CTNM4.SA', 'CYRE3': 'CYRE3.SA', 'DASA3': 'DASA3.SA', 'DIRR3': 'DIRR3.SA', 'DTEX3': 'DTEX3.SA', 'ECOR3': 'ECOR3.SA', 'EEEL3': 'EEEL3.SA', 'ELEK4': 'ELEK4.SA', 'ELET3': 'ELET3.SA', 'ELET6': 'ELET6.SA', 'EMBR3': 'EMBR3.SA', 'ENBR3': 'ENBR3.SA', 'ENGI4': 'ENGI4.SA', 'EQTL3': 'EQTL3.SA', 'YDUQ3': 'YDUQ3.SA', 'ETER3': 'ETER3.SA', 'EUCA4': 'EUCA4.SA', 'EVEN3': 'EVEN3.SA', 'EZTC3': 'EZTC3.SA', 'FESA4': 'FESA4.SA', 'FHER3': 'FHER3.SA', 'TASA4': 'TASA4.SA', 'FLRY3': 'FLRY3.SA', 'FRIO3': 'FRIO3.SA', 'TIET3': 'TIET3.SA', 'TIET4': 'TIET4.SA', 'GFSA3': 'GFSA3.SA', 'GGBR3': 'GGBR3.SA', 'GGBR4': 'GGBR4.SA', 'GOAU3': 'GOAU3.SA', 'GOAU4': 'GOAU4.SA', 'GOLL4': 'GOLL4.SA', 'GRND3': 'GRND3.SA', 'GSHP3': 'GSHP3.SA', 'HBOR3': 'HBOR3.SA', 'HGTX3': 'HGTX3.SA', 'PRIO3': 'PRIO3.SA', 'HYPE3': 'HYPE3.SA', 'IDNT3': 'IDNT3.SA', 'IDVL4': 'IDVL4.SA', 'IGTA3': 'IGTA3.SA', 'MEAL3': 'MEAL3.SA', 'INEP3': 'INEP3.SA', 'INEP4': 'INEP4.SA', 'ITSA3': 'ITSA3.SA', 'ITSA4': 'ITSA4.SA', 'ITUB3': 'ITUB3.SA', 'ITUB4': 'ITUB4.SA', 'JBSS3': 'JBSS3.SA', 'JFEN3': 'JFEN3.SA', 'JHSF3': 'JHSF3.SA', 'JSLG3': 'JSLG3.SA', 'KEPL3': 'KEPL3.SA', 'KLBN4': 'KLBN4.SA', 'LAME3': 'LAME3.SA', 'LAME4': 'LAME4.SA', 'LEVE3': 'LEVE3.SA', 'LIGT3': 'LIGT3.SA', 'LLIS3': 'LLIS3.SA', 'LOGN3': 'LOGN3.SA', 'LPSB3': 'LPSB3.SA', 'LREN3': 'LREN3.SA', 'LUPA3': 'LUPA3.SA', 'MDIA3': 'MDIA3.SA', 'MGEL4': 'MGEL4.SA', 'MGLU3': 'MGLU3.SA', 'MILS3': 'MILS3.SA', 'MMXM3': 'MMXM3.SA', 'ENEV3': 'ENEV3.SA', 'MRFG3': 'MRFG3.SA', 'MRVE3': 'MRVE3.SA', 'MTIG4': 'MTIG4.SA', 'MULT3': 'MULT3.SA', 'MYPK3': 'MYPK3.SA', 'NATU3': 'NATU3.SA', 'ODPV3': 'ODPV3.SA', 'OSXB3': 'OSXB3.SA', 'PCAR4': 'PCAR4.SA', 'PDGR3': 'PDGR3.SA', 'PETR3': 'PETR3.SA', 'PETR4': 'PETR4.SA', 'PFRM3': 'PFRM3.SA', 'PINE4': 'PINE4.SA', 'PLAS3': 'PLAS3.SA', 'PMAM3': 'PMAM3.SA', 'POMO3': 'POMO3.SA', 'POMO4': 'POMO4.SA', 'POSI3': 'POSI3.SA', 'PSSA3': 'PSSA3.SA', 'PTBL3': 'PTBL3.SA', 'PTNT4': 'PTNT4.SA', 'ENAT3': 'ENAT3.SA', 'QUAL3': 'QUAL3.SA', 'RAPT3': 'RAPT3.SA', 'RAPT4': 'RAPT4.SA', 'RDNI3': 'RDNI3.SA', 'RENT3': 'RENT3.SA', 'FRTA3': 'FRTA3.SA', 'RNEW11': 'RNEW11.SA', 'ROMI3': 'ROMI3.SA', 'RSID3': 'RSID3.SA', 'SANB11': 'SANB11.SA', 'SBSP3': 'SBSP3.SA', 'SCAR3': 'SCAR3.SA', 'SGPS3': 'SGPS3.SA', 'SHOW3': 'SHOW3.SA', 'SLCE3': 'SLCE3.SA', 'SLED4': 'SLED4.SA', 'SMTO3': 'SMTO3.SA', 'SULA11': 'SULA11.SA', 'EGIE3': 'EGIE3.SA', 'TCSA3': 'TCSA3.SA', 'TECN3': 'TECN3.SA', 'TEKA4': 'TEKA4.SA', 'TGMA3': 'TGMA3.SA', 'TIMP3': 'TIMP3.SA', 'TOTS3': 'TOTS3.SA', 'TPIS3': 'TPIS3.SA', 'TRIS3': 'TRIS3.SA', 'TAEE11': 'TAEE11.SA', 'TRPL4': 'TRPL4.SA', 'TRPN3': 'TRPN3.SA', 'UGPA3': 'UGPA3.SA', 'UNIP3': 'UNIP3.SA', 'UNIP6': 'UNIP6.SA', 'USIM3': 'USIM3.SA', 'USIM5': 'USIM5.SA', 'TESA3': 'TESA3.SA', 'VALE3': 'VALE3.SA', 'VIVR3': 'VIVR3.SA', 'VIVT3': 'VIVT3.SA', 'VIVT4': 'VIVT4.SA', 'VLID3': 'VLID3.SA', 'WEGE3': 'WEGE3.SA', 'BRSR5': 'BRSR5.SA', 'CESP5': 'CESP5.SA', 'ELPL3': 'ELPL3.SA', 'SANB4': 'SANB4.SA', 'STBP3': 'STBP3.SA', 'CCXC3': 'CCXC3.SA', 'CESP3': 'CESP3.SA', 'CGRA3': 'CGRA3.SA', 'CLSC4': 'CLSC4.SA', 'COCE3': 'COCE3.SA', 'TASA3': 'TASA3.SA', 'COGN3': 'COGN3.SA', 'LCAM3': 'LCAM3.SA', 'RADL3': 'RADL3.SA', 'UCAS3': 'UCAS3.SA', 'ALUP11': 'ALUP11.SA', 'ANIM3': 'ANIM3.SA', 'BBSE3': 'BBSE3.SA', 'BSEV3': 'BSEV3.SA', 'CPRE3': 'CPRE3.SA', 'CVCB3': 'CVCB3.SA', 'LINX3': 'LINX3.SA', 'SEER3': 'SEER3.SA', 'SMLS3': 'SMLS3.SA', 'TUPY3': 'TUPY3.SA', 'SQIA3': 'SQIA3.SA', 'BIOM3': 'BIOM3.SA', 'KLBN11': 'KLBN11.SA', 'NUTR3': 'NUTR3.SA', 'BAZA3': 'BAZA3.SA', 'HGBS11': 'HGBS11.SA', 'HGPO11': 'HGPO11.SA', 'MBRF11': 'MBRF11.SA', 'TCNO3': 'TCNO3.SA', 'ABCP11': 'ABCP11.SA', 'RBED11': 'RBED11.SA', 'BBPO11': 'BBPO11.SA', 'BBRC11': 'BBRC11.SA', 'BBVJ11': 'BBVJ11.SA', 'BPFF11': 'BPFF11.SA', 'BRCR11': 'BRCR11.SA', 'CTXT11': 'CTXT11.SA', 'CXTL11': 'CXTL11.SA', 'EURO11': 'EURO11.SA', 'RCRB11': 'RCRB11.SA', 'FIGS11': 'FIGS11.SA', 'FIXX11': 'FIXX11.SA', 'FLMA11': 'FLMA11.SA', 'FPAB11': 'FPAB11.SA', 'HMOC11': 'HMOC11.SA', 'HGCR11': 'HGCR11.SA', 'HGLG11': 'HGLG11.SA', 'HGRE11': 'HGRE11.SA', 'JSRE11': 'JSRE11.SA', 'KNCR11': 'KNCR11.SA', 'KNRE11': 'KNRE11.SA', 'KNRI11': 'KNRI11.SA', 'MXRF11': 'MXRF11.SA', 'ONEF11': 'ONEF11.SA', 'PQDP11': 'PQDP11.SA', 'PRSV11': 'PRSV11.SA', 'RBBV11': 'RBBV11.SA', 'RBCB11': 'RBCB11.SA', 'RBGS11': 'RBGS11.SA', 'RBRD11': 'RBRD11.SA', 'RBVO11': 'RBVO11.SA', 'RDES11': 'RDES11.SA', 'RNDP11': 'RNDP11.SA', 'RNGO11': 'RNGO11.SA', 'SAAG11': 'SAAG11.SA', 'SDIL11': 'SDIL11.SA', 'SHPH11': 'SHPH11.SA', 'SPTW11': 'SPTW11.SA', 'TBOF11': 'TBOF11.SA', 'TRXL11': 'TRXL11.SA', 'VLOL11': 'VLOL11.SA', 'VRTA11': 'VRTA11.SA', 'XPCM11': 'XPCM11.SA', 'XTED11': 'XTED11.SA', 'SANB3': 'SANB3.SA', 'SEDU3': 'SEDU3.SA', 'FRAS3': 'FRAS3.SA', 'GEPA4': 'GEPA4.SA', 'OFSA3': 'OFSA3.SA', 'RLOG3': 'RLOG3.SA', 'TOYB3': 'TOYB3.SA', 'AAPL34': 'AAPL34.SA', 'ABTT34': 'ABTT34.SA', 'AMGN34': 'AMGN34.SA', 'AMZO34': 'AMZO34.SA', 'ARMT34': 'ARMT34.SA', 'ATTB34': 'ATTB34.SA', 'AXPB34': 'AXPB34.SA', 'BERK34': 'BERK34.SA', 'BOAC34': 'BOAC34.SA', 'CATP34': 'CATP34.SA', 'CMCS34': 'CMCS34.SA', 'COCA34': 'COCA34.SA', 'CSCO34': 'CSCO34.SA', 'DISB34': 'DISB34.SA', 'EXXO34': 'EXXO34.SA', 'FDMO34': 'FDMO34.SA', 'GEOO34': 'GEOO34.SA', 'GSGI34': 'GSGI34.SA', 'HALI34': 'HALI34.SA', 'HOME34': 'HOME34.SA', 'HPQB34': 'HPQB34.SA', 'ITLC34': 'ITLC34.SA', 'JNJB34': 'JNJB34.SA', 'JPMC34': 'JPMC34.SA', 'LMTB34': 'LMTB34.SA', 'MMMC34': 'MMMC34.SA', 'MRCK34': 'MRCK34.SA', 'MSCD34': 'MSCD34.SA', 'MSFT34': 'MSFT34.SA', 'NIKE34': 'NIKE34.SA', 'ORCL34': 'ORCL34.SA', 'PFIZ34': 'PFIZ34.SA', 'PGCO34': 'PGCO34.SA', 'SBUB34': 'SBUB34.SA', 'VERZ34': 'VERZ34.SA', 'VISA34': 'VISA34.SA', 'WALM34': 'WALM34.SA', 'WFCO34': 'WFCO34.SA', 'WIZS3': 'WIZS3.SA', 'BOEI34': 'BOEI34.SA', 'CHVX34': 'CHVX34.SA', 'COPH34': 'COPH34.SA', 'CTGP34': 'CTGP34.SA', 'FBOK34': 'FBOK34.SA', 'IBMB34': 'IBMB34.SA', 'LILY34': 'LILY34.SA', 'MCDC34': 'MCDC34.SA', 'MFII11': 'MFII11.SA', 'MSBR34': 'MSBR34.SA', 'NFLX34': 'NFLX34.SA', 'PEPB34': 'PEPB34.SA', 'SLBG34': 'SLBG34.SA', 'UPSS34': 'UPSS34.SA', 'USBC34': 'USBC34.SA', 'GUAR3': 'GUAR3.SA', 'ACNB34': 'ACNB34.SA', 'BONY34': 'BONY34.SA', 'DHER34': 'DHER34.SA', 'IGBR3': 'IGBR3.SA', 'KMBB34': 'KMBB34.SA', 'METB34': 'METB34.SA', 'TELB4': 'TELB4.SA', 'TGTB34': 'TGTB34.SA', 'WHRL3': 'WHRL3.SA', 'AVON34': 'AVON34.SA', 'BMYB34': 'BMYB34.SA', 'COLG34': 'COLG34.SA', 'COTY34': 'COTY34.SA', 'EBAY34': 'EBAY34.SA', 'FCXO34': 'FCXO34.SA', 'FDXB34': 'FDXB34.SA', 'GDBR34': 'GDBR34.SA', 'HSHY34': 'HSHY34.SA', 'MDLZ34': 'MDLZ34.SA', 'MOSC34': 'MOSC34.SA', 'QCOM34': 'QCOM34.SA', 'TEXA34': 'TEXA34.SA', 'TIFF34': 'TIFF34.SA', 'UTEC34': 'UTEC34.SA', 'WUNI34': 'WUNI34.SA', 'XRXB34': 'XRXB34.SA', 'SHUL4': 'SHUL4.SA', 'ATOM3': 'ATOM3.SA', 'KHCB34': 'KHCB34.SA', 'TIET11': 'TIET11.SA', 'SAPR4': 'SAPR4.SA', 'CRIV4': 'CRIV4.SA', 'RPMG3': 'RPMG3.SA', 'BRSR3': 'BRSR3.SA', 'DOMC11': 'DOMC11.SA', 'ENGI11': 'ENGI11.SA', 'SNSY5': 'SNSY5.SA', 'DMMO3': 'DMMO3.SA', 'ABCB10': 'ABCB10.SA', 'ANIM3T': 'ANIM3T.SA', 'AZEV4': 'AZEV4.SA', 'BAHI3': 'BAHI3.SA', 'BALM4': 'BALM4.SA', 'BAUH4': 'BAUH4.SA', 'BDLL4': 'BDLL4.SA', 'BEES3': 'BEES3.SA', 'BEES4': 'BEES4.SA', 'BGIP4': 'BGIP4.SA', 'BMEB3': 'BMEB3.SA', 'BMEB4': 'BMEB4.SA', 'BMIN3': 'BMIN3.SA', 'BMIN4': 'BMIN4.SA', 'BMKS3': 'BMKS3.SA', 'BNBR3': 'BNBR3.SA', 'BOBR4': 'BOBR4.SA', 'BRIV3': 'BRIV3.SA', 'BRIV4': 'BRIV4.SA', 'BSLI4': 'BSLI4.SA', 'BTTL3': 'BTTL3.SA', 'CBEE3': 'CBEE3.SA', 'CEEB3': 'CEEB3.SA', 'CEEB5': 'CEEB5.SA', 'CELP3': 'CELP3.SA', 'CELP5': 'CELP5.SA', 'CEPE5': 'CEPE5.SA', 'CGAS3': 'CGAS3.SA', 'CPRE3T': 'CPRE3T.SA', 'CRIV3': 'CRIV3.SA', 'CRPG5': 'CRPG5.SA', 'CRPG6': 'CRPG6.SA', 'CSRN3': 'CSRN3.SA', 'CTKA4': 'CTKA4.SA', 'CTNM3': 'CTNM3.SA', 'CTSA3': 'CTSA3.SA', 'CTSA4': 'CTSA4.SA', 'CVCB3T': 'CVCB3T.SA', 'DOHL4': 'DOHL4.SA', 'DTCY3': 'DTCY3.SA', 'EALT4': 'EALT4.SA', 'EKTR4': 'EKTR4.SA', 'ELEK3': 'ELEK3.SA', 'EMAE4': 'EMAE4.SA', 'ENGI3': 'ENGI3.SA', 'ENMT3': 'ENMT3.SA', 'ESTR4': 'ESTR4.SA', 'FESA3': 'FESA3.SA', 'FNAM11': 'FNAM11.SA', 'FSRF11': 'FSRF11.SA', 'GPCP3': 'GPCP3.SA', 'HAGA4': 'HAGA4.SA', 'HBTS5': 'HBTS5.SA', 'HETA4': 'HETA4.SA', 'HOOT4': 'HOOT4.SA', 'IDVL3': 'IDVL3.SA', 'JBDU3': 'JBDU3.SA', 'JBDU4': 'JBDU4.SA', 'JOPA3': 'JOPA3.SA', 'JOPA4': 'JOPA4.SA', 'KLBN3': 'KLBN3.SA', 'MEND5': 'MEND5.SA', 'MNDL3': 'MNDL3.SA', 'MNPR3': 'MNPR3.SA', 'MTSA4': 'MTSA4.SA', 'MWET4': 'MWET4.SA', 'DMMO3T': 'DMMO3T.SA', 'PEAB4': 'PEAB4.SA', 'PNVL3': 'PNVL3.SA', 'PNVL4': 'PNVL4.SA', 'RANI3': 'RANI3.SA', 'RANI4': 'RANI4.SA', 'RCSL3': 'RCSL3.SA', 'RCSL4': 'RCSL4.SA', 'REDE3': 'REDE3.SA', 'RPAD5': 'RPAD5.SA', 'RPAD6': 'RPAD6.SA', 'SEER3T': 'SEER3T.SA', 'WLMM3': 'WLMM3.SA', 'WLMM4': 'WLMM4.SA', 'SLED3': 'SLED3.SA', 'SMLS3T': 'SMLS3T.SA', 'SOND5': 'SOND5.SA', 'SOND6': 'SOND6.SA', 'SPRI3': 'SPRI3.SA', 'TCNO4': 'TCNO4.SA', 'TELB3': 'TELB3.SA', 'TOYB4': 'TOYB4.SA', 'TRPL3': 'TRPL3.SA', 'UNIP5': 'UNIP5.SA', 'USIM6': 'USIM6.SA', 'VULC3': 'VULC3.SA', 'VVAR3': 'VVAR3.SA', 'WHRL4': 'WHRL4.SA', 'ALMI11': 'ALMI11.SA', 'ANCR11B': 'ANCR11B.SA', 'ATSA11B': 'ATSA11B.SA', 'BBFI11B': 'BBFI11B.SA', 'BCFF11': 'BCFF11.SA', 'BMLC11B': 'BMLC11B.SA', 'CEOC11': 'CEOC11.SA', 'CNES11': 'CNES11.SA', 'MRSA6BF': 'MRSA6BF.SA', 'CPTS11B': 'CPTS11B.SA', 'CXCE11B': 'CXCE11B.SA', 'DRIT11B': 'DRIT11B.SA', 'EDFO11B': 'EDFO11B.SA', 'EDGA11': 'EDGA11.SA', 'ENMA3B': 'ENMA3B.SA', 'FAED11': 'FAED11.SA', 'FAMB11B': 'FAMB11B.SA', 'FCFL11': 'FCFL11.SA', 'FEXC11': 'FEXC11.SA', 'FIIP11B': 'FIIP11B.SA', 'FLRP11': 'FLRP11.SA', 'FVBI11': 'FVBI11.SA', 'HCRI11': 'HCRI11.SA', 'HTMX11': 'HTMX11.SA', 'JRDM11': 'JRDM11.SA', 'MAXR11': 'MAXR11.SA', 'NSLU11': 'NSLU11.SA', 'TRNT11': 'TRNT11.SA', 'WPLZ11B': 'WPLZ11B.SA', 'ARNC34': 'ARNC34.SA', 'ABBV34': 'ABBV34.SA', 'BBYY34': 'BBYY34.SA', 'BCRI11': 'BCRI11.SA', 'BIIB34': 'BIIB34.SA', 'BLAK34': 'BLAK34.SA', 'CHKE34': 'CHKE34.SA', 'COWC34': 'COWC34.SA', 'CTSH34': 'CTSH34.SA', 'CVSH34': 'CVSH34.SA', 'CXRI11': 'CXRI11.SA', 'DEAI34': 'DEAI34.SA', 'FSLR34': 'FSLR34.SA', 'GILD34': 'GILD34.SA', 'GOGL34': 'GOGL34.SA', 'GOGL35': 'GOGL35.SA', 'GPSI34': 'GPSI34.SA', 'JCPC34': 'JCPC34.SA', 'MACY34': 'MACY34.SA', 'MDTC34': 'MDTC34.SA', 'RIGG34': 'RIGG34.SA', 'ROST34': 'ROST34.SA', 'SANC34': 'SANC34.SA', 'SCHW34': 'SCHW34.SA', 'SPRN34': 'SPRN34.SA', 'SSFO34': 'SSFO34.SA', 'TMOS34': 'TMOS34.SA', 'TRVC34': 'TRVC34.SA', 'USSX34': 'USSX34.SA', 'VLOE34': 'VLOE34.SA', 'WSON33': 'WSON33.SA', 'AALR3': 'AALR3.SA', 'AFLT3': 'AFLT3.SA', 'BGIP3': 'BGIP3.SA', 'BNFS11': 'BNFS11.SA', 'CBOP11': 'CBOP11.SA', 'CEBR3': 'CEBR3.SA', 'CEDO3': 'CEDO3.SA', 'ESUD11': 'ESUD11.SA', 'ESUT11': 'ESUT11.SA', 'FIIB11': 'FIIB11.SA', 'FIVN11': 'FIVN11.SA', 'FMOF11': 'FMOF11.SA', 'FNOR11': 'FNOR11.SA', 'FSPE11': 'FSPE11.SA', 'FSTU11': 'FSTU11.SA', 'GPAR3': 'GPAR3.SA', 'GRLV11': 'GRLV11.SA', 'MAPT3': 'MAPT3.SA', 'MMXM11': 'MMXM11.SA', 'PABY11': 'PABY11.SA', 'PATI4': 'PATI4.SA', 'PLRI11': 'PLRI11.SA', 'PORD11': 'PORD11.SA', 'RBDS11': 'RBDS11.SA', 'RPAD3': 'RPAD3.SA', 'SCPF11': 'SCPF11.SA', 'VSPT3': 'VSPT3.SA', 'XPOM11': 'XPOM11.SA', 'POMO10': 'POMO10.SA', 'AIGB34': 'AIGB34.SA', 'DUKB34': 'DUKB34.SA', 'MOVI3': 'MOVI3.SA', 'PARD3': 'PARD3.SA', 'BPAC11': 'BPAC11.SA', 'PPLA11': 'PPLA11.SA', 'AALL34': 'AALL34.SA', 'GMCO34': 'GMCO34.SA', 'LBRN34': 'LBRN34.SA', 'TWTR34': 'TWTR34.SA', 'UPAC34': 'UPAC34.SA', 'RNEW3': 'RNEW3.SA', 'RNEW4': 'RNEW4.SA', 'AZUL4': 'AZUL4.SA', 'KNIP11': 'KNIP11.SA', 'TEND3': 'TEND3.SA', 'TSLA34': 'TSLA34.SA', 'CRFB3': 'CRFB3.SA', 'GBIO33': 'GBIO33.SA', 'OMGE3': 'OMGE3.SA', 'IRBR3': 'IRBR3.SA', 'GGRC11': 'GGRC11.SA', 'GEPA3': 'GEPA3.SA', 'SAPR3': 'SAPR3.SA', 'CAML3': 'CAML3.SA', 'VISC11': 'VISC11.SA', 'SUZB3': 'SUZB3.SA', 'SAPR11': 'SAPR11.SA', 'BRDT3': 'BRDT3.SA', 'NEOE3': 'NEOE3.SA', 'BKBR3': 'BKBR3.SA', 'FMXB34': 'FMXB34.SA', 'CLGN34': 'CLGN34.SA', 'HONB34': 'HONB34.SA', 'ALZR11': 'ALZR11.SA', 'GFSA1': 'GFSA1.SA', 'DDNB34': 'DDNB34.SA', 'UBSG34': 'UBSG34.SA', 'TXRX4': 'TXRX4.SA', 'OUJP11': 'OUJP11.SA', 'BCIA11': 'BCIA11.SA', 'BOXP34': 'BOXP34.SA', 'GPRO34': 'GPRO34.SA', 'MSPA3': 'MSPA3.SA', 'HFOF11': 'HFOF11.SA', 'RBRF11': 'RBRF11.SA', 'HAPV3': 'HAPV3.SA', 'GNDI3': 'GNDI3.SA', 'BIDI4': 'BIDI4.SA', 'JPSA3': 'JPSA3.SA', 'GPIV33': 'GPIV33.SA', 'IRDM11': 'IRDM11.SA', 'FOFT11': 'FOFT11.SA', 'THRA11': 'THRA11.SA', 'TAEE4': 'TAEE4.SA', 'BIDI4T': 'BIDI4T.SA', 'XPLG11': 'XPLG11.SA', 'RBRR11': 'RBRR11.SA', 'WPLZ11': 'WPLZ11.SA', 'MGFF11': 'MGFF11.SA', 'TGAR11': 'TGAR11.SA', 'HGRU11': 'HGRU11.SA', 'ALUP3': 'ALUP3.SA', 'ALUP4': 'ALUP4.SA', 'LOGG3': 'LOGG3.SA', 'KNHY11': 'KNHY11.SA', 'OUCY11': 'OUCY11.SA', 'FVPQ11': 'FVPQ11.SA', 'TASA13': 'TASA13.SA', 'TASA15': 'TASA15.SA', 'TASA17': 'TASA17.SA', 'CARE11': 'CARE11.SA', 'TAEE3': 'TAEE3.SA', 'XPIN11': 'XPIN11.SA', 'VSHO11': 'VSHO11.SA', 'DMMO11': 'DMMO11.SA', 'AZEV3': 'AZEV3.SA', 'AHEB3': 'AHEB3.SA', 'BALM3': 'BALM3.SA', 'BPAC3': 'BPAC3.SA', 'EALT3': 'EALT3.SA', 'ECPR3': 'ECPR3.SA', 'HAGA3': 'HAGA3.SA', 'ITEC3': 'ITEC3.SA', 'LIPR3': 'LIPR3.SA', 'PATI3': 'PATI3.SA', 'PEAB3': 'PEAB3.SA', 'SULA3': 'SULA3.SA', 'BPAC5': 'BPAC5.SA', 'BRGE11': 'BRGE11.SA', 'BRGE12': 'BRGE12.SA', 'BRGE6': 'BRGE6.SA', 'CELP6': 'CELP6.SA', 'CELP7': 'CELP7.SA', 'CORR4': 'CORR4.SA', 'EEEL4': 'EEEL4.SA', 'ENMT4': 'ENMT4.SA', 'LUXM4': 'LUXM4.SA', 'MEND6': 'MEND6.SA', 'MERC4': 'MERC4.SA', 'RSUL4': 'RSUL4.SA', 'SULA4': 'SULA4.SA', 'BEEF11': 'BEEF11.SA', 'JBDU1': 'JBDU1.SA', 'JBDU2': 'JBDU2.SA', 'LOGN12': 'LOGN12.SA', 'MYPK12': 'MYPK12.SA', 'PATC11': 'PATC11.SA', 'VGIR11': 'VGIR11.SA', 'VILG11': 'VILG11.SA', 'CNTO3': 'CNTO3.SA', 'BTCR11': 'BTCR11.SA', 'VAMO3': 'VAMO3.SA', 'CAMB10': 'CAMB10.SA', 'IDVL9': 'IDVL9.SA', 'MELI34': 'MELI34.SA', 'MOAR3': 'MOAR3.SA', 'RBVA11': 'RBVA11.SA', 'MRSA3B': 'MRSA3B.SA', 'VTLT11': 'VTLT11.SA', 'GTWR11': 'GTWR11.SA', 'BIDI11': 'BIDI11.SA', 'BIDI3': 'BIDI3.SA', 'DMAC11': 'DMAC11.SA', 'TFOF11': 'TFOF11.SA', 'HCTR11': 'HCTR11.SA', 'TIET2': 'TIET2.SA', 'HSML11': 'HSML11.SA', 'XPHT11': 'XPHT11.SA', 'XPHT12': 'XPHT12.SA', 'HABT11': 'HABT11.SA', 'RECT11': 'RECT11.SA', 'AQLL11': 'AQLL11.SA', 'ARFI11B': 'ARFI11B.SA', 'ATCR11': 'ATCR11.SA', 'BARI11': 'BARI11.SA', 'BBIM11': 'BBIM11.SA', 'BMII11': 'BMII11.SA', 'BPRP11': 'BPRP11.SA', 'BRHT11B': 'BRHT11B.SA', 'BVAR11': 'BVAR11.SA', 'DAMT11B': 'DAMT11B.SA', 'DOVL11B': 'DOVL11B.SA', 'ELDO11B': 'ELDO11B.SA', 'ERPA11': 'ERPA11.SA', 'FINF11': 'FINF11.SA', 'FISC11': 'FISC11.SA', 'FISD11': 'FISD11.SA', 'FPNG11': 'FPNG11.SA', 'FTCE11B': 'FTCE11B.SA', 'GESE11B': 'GESE11B.SA', 'HBTT11': 'HBTT11.SA', 'HGFF11': 'HGFF11.SA', 'HUSC11': 'HUSC11.SA', 'JPPC11': 'JPPC11.SA', 'KINP11': 'KINP11.SA', 'LATR11B': 'LATR11B.SA', 'NCHB11': 'NCHB11.SA', 'NPAR11': 'NPAR11.SA', 'NVHO11': 'NVHO11.SA', 'NVIF11B': 'NVIF11B.SA', 'ORPD11': 'ORPD11.SA', 'OULG11B': 'OULG11B.SA', 'PBLV11': 'PBLV11.SA', 'PRSN11B': 'PRSN11B.SA', 'PRTS11': 'PRTS11.SA', 'RBCO11': 'RBCO11.SA', 'RBFF11': 'RBFF11.SA', 'RBRP11': 'RBRP11.SA', 'RBRY11': 'RBRY11.SA', 'RCFA11': 'RCFA11.SA', 'RCRI11B': 'RCRI11B.SA', 'RDPD11': 'RDPD11.SA', 'REIT11': 'REIT11.SA', 'SADI11': 'SADI11.SA', 'SAIC11B': 'SAIC11B.SA', 'SFND11': 'SFND11.SA', 'SHDP11B': 'SHDP11B.SA', 'SHOP11': 'SHOP11.SA', 'SPAF11': 'SPAF11.SA', 'STRX11': 'STRX11.SA', 'TCR11': 'TCR11.SA', 'TORM13': 'TORM13.SA', 'TOUR11': 'TOUR11.SA', 'TSNC11': 'TSNC11.SA', 'VERE11': 'VERE11.SA', 'VLJS11': 'VLJS11.SA', 'VPSI11': 'VPSI11.SA', 'WTSP11B': 'WTSP11B.SA', 'YCHY11': 'YCHY11.SA', 'VIVA3': 'VIVA3.SA', 'CEAB3': 'CEAB3.SA', 'BMGB11': 'BMGB11.SA', 'BMGB4': 'BMGB4.SA', 'SDIP11': 'SDIP11.SA', 'IBFF11': 'IBFF11.SA', 'CVBI11': 'CVBI11.SA', 'HRDF11': 'HRDF11.SA', 'RSPD11': 'RSPD11.SA', 'TCPF11': 'TCPF11.SA'}

,country,name,full_name,isin,currency,symbol
0,brazil,ABC BRASIL PN,Banco ABC Brasil SA,BRABCBACNPR4,BRL,ABCB4
1,brazil,BRASILAGRO ON,BrasilAgro - Co ON NM,BRAGROACNOR7,BRL,AGRO3
2,brazil,RUMO ON NM,RUMO Logistica Operadora Multimodal SA,BRRAILACNOR9,BRL,RAIL3

#### Ticker único e infos interessantes

In [77]:
TickerYF = yf.Ticker('PETR4.SA')

In [78]:
### COTAÇÃO HISTORICA

df_history = TickerYF.history(period='1d', interval='1wk', start='2020-01-01', end=date.today())
df_history['Ativo'] = 'PETR4'
df_history = df_history[['Ativo', 'Open', 'Close', 'Low', 'High', 'Volume', 'Dividends', 'Stock Splits']]
df_history.head(3)

,Ativo,Open,Close,Low,High,Volume,Dividends,Stock Splits
Date,,,,,,,,
2020-01-01 00:00:00-03:00,PETR4,11.107358,11.295057,11.022710,11.497477,224036100,0.0,0.0
2020-01-08 00:00:00-03:00,PETR4,11.295058,11.041112,10.956464,11.324501,180189100,0.0,0.0
2020-01-15 00:00:00-03:00,PETR4,11.004309,10.901259,10.794528,11.077917,158129900,0.0,0.0

In [79]:
df_history.dtypes

Ativo            object
Open            float64
Close           float64
Low             float64
High            float64
Volume            int64
Dividends       float64
Stock Splits    float64
dtype: object

In [127]:
### INFORMAÇÔES GERAIS
"""get info de forma rapido, pode ser útil em alguns casos."""

dic = TickerYF.get_fast_info()

for i in dic:
    valor = dic[i]
    print(i + ' ---> ' + f'{valor}')

currency ---> BRL
dayHigh ---> 36.0
dayLow ---> 35.529998779296875
exchange ---> SAO
fiftyDayAverage ---> 35.287999649047855
lastPrice ---> 35.66999816894531
lastVolume ---> 36388100
marketCap ---> 475994737262.9531
open ---> 35.720001220703125
previousClose ---> 35.529998779296875
quoteType ---> EQUITY
regularMarketPreviousClose ---> 35.90999984741211
shares ---> 13344400384
tenDayAverageVolume ---> 46009470
threeMonthAverageVolume ---> 50123626
timezone ---> America/Sao_Paulo
twoHundredDayAverage ---> 29.855349912643433
yearChange ---> 0.3922715456871402
yearHigh ---> 38.86000061035156
yearLow ---> 20.770000457763672

In [132]:
### Metadados dO Ticker (???)

TickerYF.get_history_metadata()

{'currency': 'BRL',
 'symbol': 'PETR4.SA',
 'exchangeName': 'SAO',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 946900800,
 'regularMarketTime': 1701467209,
 'gmtoffset': -10800,
 'timezone': 'BRT',
 'exchangeTimezoneName': 'America/Sao_Paulo',
 'regularMarketPrice': 35.67,
 'chartPreviousClose': 35.27,
 'previousClose': 35.91,
 'scale': 3,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'BRT',
   'start': 1701434700,
   'end': 1701435600,
   'gmtoffset': -10800},
  'regular': {'timezone': 'BRT',
   'start': 1701435600,
   'end': 1701460800,
   'gmtoffset': -10800},
  'post': {'timezone': 'BRT',
   'start': 1701460800,
   'end': 1701464400,
   'gmtoffset': -10800}},
 'tradingPeriods': {'pre': [[{'timezone': 'BRT',
     'start': 1700829900,
     'end': 1700830800,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701089100,
     'end': 1701090000,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701175500,
     'end': 1701176400,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701261900,
     'end': 1701262800,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701348300,
     'end': 1701349200,
     'gmtoffset': -10800}]],
  'post': [[{'timezone': 'BRT',
     'start': 1700856000,
     'end': 1700859600,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701115200,
     'end': 1701118800,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701201600,
     'end': 1701205200,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701288000,
     'end': 1701291600,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701374400,
     'end': 1701378000,
     'gmtoffset': -10800}]],
  'regular': [[{'timezone': 'BRT',
     'start': 1701090000,
     'end': 1701115200,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701176400,
     'end': 1701201600,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701262800,
     'end': 1701288000,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701349200,
     'end': 1701374400,
     'gmtoffset': -10800}],
   [{'timezone': 'BRT',
     'start': 1701435600,
     'end': 1701460800,
     'gmtoffset': -10800}]]},
 'dataGranularity': '1h',
 'range': '1wk',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [134]:
TickerYF.get_major_holders()

        0                                      1
0  16.07%        % of Shares Held by All Insider
1  35.61%       % of Shares Held by Institutions
2  42.43%        % of Float Held by Institutions
3     459  Number of Institutions Holding Shares

In [92]:
### EVNTEOS (DIVIDENDOS E SPLITS)

TickerYF.get_actions().head(3)

                           Dividends  Stock Splits
Date
2022-08-12 00:00:00-03:00   6.732003           0.0
2022-11-22 00:00:00-03:00   3.348900           0.0
2023-04-28 00:00:00-03:00   2.870493           0.0

In [84]:
### BALANÇO FINANCEIRO

TickerYF.get_balance_sheet()

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
TreasurySharesNumber,295669.0,295669.0,295669.0,295669.0
PreferredSharesNumber,NaN,5601969879.0,NaN,NaN
OrdinarySharesNumber,13044201261.0,13044201261.0,13044201261.0,13044201261.0
ShareIssued,13044496930.0,13044496930.0,13044496930.0,13044496930.0
NetDebt,21958000000.0,25233000000.0,42177000000.0,55888000000.0
...,...,...,...,...
CashCashEquivalentsAndShortTermInvestments,10769000000.0,11117000000.0,12370000000.0,8260000000.0
OtherShortTermInvestments,2773000000.0,650000000.0,659000000.0,888000000.0
CashAndCashEquivalents,7996000000.0,10467000000.0,11711000000.0,7372000000.0
CashEquivalents,7780000000.0,10168000000.0,11159000000.0,6800000000.0
CashFinancial,216000000.0,299000000.0,552000000.0,572000000.0

In [86]:
### FLUXO DE CAIXA

TickerYF.get_cashflow()

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
FreeCashFlow,40136000000.0,31466000000.0,23016000000.0,1703000000.0
RepaymentOfDebt,-14764000000.0,-27240000000.0,-31607000000.0,-32480000000.0
IssuanceOfDebt,2880000000.0,1885000000.0,17023000000.0,7464000000.0
CapitalExpenditure,-9581000000.0,-6325000000.0,-5874000000.0,-23897000000.0
EndCashPosition,7996000000.0,10480000000.0,11725000000.0,7377000000.0
...,...,...,...,...
OperatingGainsLosses,4390000000.0,9386000000.0,10296000000.0,4381000000.0
PensionAndEmployeeBenefitExpense,1228000000.0,2098000000.0,-1001000000.0,2086000000.0
EarningsLossesFromEquityInvestments,-251000000.0,-1607000000.0,659000000.0,-153000000.0
NetForeignCurrencyExchangeGainLoss,4557000000.0,10795000000.0,11094000000.0,8460000000.0
NetIncomeFromContinuingOperations,36755000000.0,19986000000.0,948000000.0,10363000000.0

In [102]:
### INFO FINANCEIRAS

TickerYF.get_financials()

,2022-12-31,2021-12-31,2020-12-31,2019-12-31
TaxEffectOfUnusualItems,-1209745000.0,-786390292.294066,-4673640000.0,-931350000.0
TaxRateForCalcs,0.313,0.291904,0.34,0.35
NormalizedEBITDA,73919000000.0,47591000000.0,30736000000.0,36184000000.0
TotalUnusualItems,-3865000000.0,-2694000000.0,-13746000000.0,-2661000000.0
TotalUnusualItemsExcludingGoodwill,-3865000000.0,-2694000000.0,-13746000000.0,-2661000000.0
...,...,...,...,...
SalariesAndWages,2057000000.0,2770000000.0,299000000.0,3443000000.0
GrossProfit,64988000000.0,40802000000.0,24488000000.0,30857000000.0
CostOfRevenue,59486000000.0,43164000000.0,29195000000.0,45732000000.0
TotalRevenue,124474000000.0,83966000000.0,53683000000.0,76589000000.0
OperatingRevenue,124474000000.0,83966000000.0,53683000000.0,76589000000.0

In [100]:
### QTDE AÇÕES

TickerYF.get_shares_full()

2022-06-03 00:00:00-03:00    13834399744
2022-06-05 00:00:00-03:00    13899499520
2022-06-08 00:00:00-03:00    13820999680
2022-06-09 00:00:00-03:00    13829600256
2022-06-10 00:00:00-03:00    13850999808
                                ...
2023-11-29 00:00:00-03:00    13458199552
2023-11-30 00:00:00-03:00    13435700224
2023-12-01 00:00:00-03:00    13358799872
2023-12-02 00:00:00-03:00    13255199744
2023-12-02 00:00:00-03:00    13344400384
Length: 269, dtype: int64

In [151]:
tickers = {'ABCB4': 'ABCB4.SA', 'AGRO3': 'AGRO3.SA', 'RAIL3': 'RAIL3.SA', 'ALPA3': 'ALPA3.SA', 'ALPA4': 'ALPA4.SA', 'ALSO3': 'ALSO3.SA', 'AMAR3': 'AMAR3.SA', 'ABEV3': 'ABEV3.SA'}

In [155]:
### HISTORICO PARA VARIOS

result_df = pd.DataFrame()

for t in tickers:
    TickerYF = yf.Ticker(tickers[t])
    df = TickerYF.history(period='1d', interval='1wk', start='2020-01-01', end=date.today())
    df['Ativo'] = t
    df = df[['Ativo', 'Open', 'Close', 'Low', 'High', 'Volume']]
    result_df = pd.concat([result_df, df])

result_df

,Ativo,Open,Close,Low,High,Volume
Date,,,,,,
2020-01-01 00:00:00-03:00,ABCB4,15.877110,16.010796,15.586147,16.396124,4051300
2020-01-08 00:00:00-03:00,ABCB4,16.358191,16.430716,16.221202,16.591881,3468300
2020-01-15 00:00:00-03:00,ABCB4,16.374311,18.139063,16.124507,18.139063,7542000
2020-01-22 00:00:00-03:00,ABCB4,18.300222,18.284107,17.631390,18.832067,4634000
2020-01-29 00:00:00-03:00,ABCB4,18.316340,18.388865,17.357413,18.630612,3875200
...,...,...,...,...,...,...
2023-11-01 00:00:00-03:00,ABEV3,12.900000,13.570000,12.760000,13.590000,109016500
2023-11-08 00:00:00-03:00,ABEV3,13.590000,13.700000,13.290000,13.750000,104665800
2023-11-15 00:00:00-03:00,ABEV3,13.700000,13.440000,13.360000,13.800000,115033000
2023-11-22 00:00:00-03:00,ABEV3,13.490000,13.650000,13.270000,13.760000,117903900
2023-11-29 00:00:00-03:00,ABEV3,13.630000,14.080000,13.250000,14.080000,121439000

#### Classe Tickers

In [156]:
TickersYF = yf.Tickers(list(tickers.values()))

In [157]:
TickersYF.tickers

{'ABCB4.SA': yfinance.Ticker object <ABCB4.SA>,
 'AGRO3.SA': yfinance.Ticker object <AGRO3.SA>,
 'RAIL3.SA': yfinance.Ticker object <RAIL3.SA>,
 'ALPA3.SA': yfinance.Ticker object <ALPA3.SA>,
 'ALPA4.SA': yfinance.Ticker object <ALPA4.SA>,
 'ALSO3.SA': yfinance.Ticker object <ALSO3.SA>,
 'AMAR3.SA': yfinance.Ticker object <AMAR3.SA>,
 'ABEV3.SA': yfinance.Ticker object <ABEV3.SA>}

In [162]:
df_result = pd.DataFrame()

for i in TickersYF.tickers:
    ativo = i.replace(".SA", "")
    df_history = TickersYF.tickers[i].history(period='1d', interval='1wk', start='2020-01-01', end=date.today())
    df['Ativo'] = ativo
    df = df[['Ativo', 'Open', 'Close', 'Low', 'High', 'Volume']]
    df_result = pd.concat([df_result, df])

df_result

,Ativo,Open,Close,Low,High,Volume
Date,,,,,,
2020-01-01 00:00:00-03:00,ABCB4,16.550782,16.896513,16.550782,17.064947,68751200
2020-01-08 00:00:00-03:00,ABCB4,16.923105,16.931971,16.408941,17.357486,87587900
2020-01-15 00:00:00-03:00,ABCB4,16.843323,16.612835,16.462131,16.843323,64032800
2020-01-22 00:00:00-03:00,ABCB4,16.710349,16.666023,16.364616,16.914241,73110000
2020-01-29 00:00:00-03:00,ABCB4,16.719214,15.646560,15.584506,16.763538,85043200
...,...,...,...,...,...,...
2023-11-01 00:00:00-03:00,ABEV3,12.900000,13.570000,12.760000,13.590000,109016500
2023-11-08 00:00:00-03:00,ABEV3,13.590000,13.700000,13.290000,13.750000,104665800
2023-11-15 00:00:00-03:00,ABEV3,13.700000,13.440000,13.360000,13.800000,115033000
2023-11-22 00:00:00-03:00,ABEV3,13.490000,13.650000,13.270000,13.760000,117903900
2023-11-29 00:00:00-03:00,ABEV3,13.630000,14.080000,13.250000,14.080000,121439000

In [159]:
### Gerando df sem loop para multiplos ativos (Ainda não consegui arrumar desses levels de colunas para ficar com um só e ter a coluna ativo)

teste = TickersYF.download(period='1wk', interval='1wk', start='2020-01-01', end=date.today())
teste

[*********************100%%**********************]  8 of 8 completed

                Close                                                         \
             ABCB4.SA   ABEV3.SA   AGRO3.SA   ALPA3.SA   ALPA4.SA   ALSO3.SA
Date
2020-01-01  16.010798  16.896513  12.929257  26.296822  32.388802  47.738670
2020-01-08  16.430717  16.931971  13.542396  27.046751  33.830498  51.503281
2020-01-15  18.139061  16.612835  13.462423  29.612295  34.610592  50.320930
2020-01-22  18.284109  16.666025  13.202505  32.069298  36.585518  50.793869
2020-01-29  18.388865  15.646561  13.235827  31.289764  34.877209  50.604691
...               ...        ...        ...        ...        ...        ...
2023-11-01  20.049999  13.570000  25.540001   9.380000   9.000000  24.190001
2023-11-08  21.280001  13.700000  24.510000   9.690000   9.430000  25.290001
2023-11-15  21.600000  13.440000  24.010000   9.930000   9.510000  25.209999
2023-11-22  21.750000  13.650000  24.260000   9.550000   9.370000  25.240000
2023-11-29  21.959999  14.080000  24.620001   9.850000   9.620000  25.459999

                                 Dividends           ... Stock Splits  \
             AMAR3.SA   RAIL3.SA  ABCB4.SA ABEV3.SA  ...     AMAR3.SA
Date                                                 ...
2020-01-01  62.526871  25.156090  0.487007      0.0  ...          0.0
2020-01-08  64.905365  25.683699  0.000000      0.0  ...          0.0
2020-01-15  64.402222  24.120777  0.000000      0.0  ...          0.0
2020-01-22  63.441677  23.792265  0.000000      0.0  ...          0.0
2020-01-29  61.749287  23.623030  0.000000      0.0  ...          0.0
...               ...        ...       ...      ...  ...          ...
2023-11-01   2.670000  22.900000  0.000000      0.0  ...          0.0
2023-11-08   3.330000  23.410000  0.000000      0.0  ...          0.0
2023-11-15   3.620000  22.900000  0.000000      0.0  ...          0.0
2023-11-22   3.780000  22.680000  0.000000      0.0  ...          0.0
2023-11-29   4.140000  22.770000  0.000000      0.0  ...          0.0

                      Volume                                                   \
           RAIL3.SA ABCB4.SA   ABEV3.SA AGRO3.SA ALPA3.SA  ALPA4.SA  ALSO3.SA
Date
2020-01-01      0.0  4051300   68751200   183500    30300   4365600   6925900
2020-01-08      0.0  3468300   87587900   337100   355400   6343100   6796500
2020-01-15      0.0  7542000   64032800  4147300   262300   4678200   5550700
2020-01-22      0.0  4634000   73110000   528900    23400   7754400   5406700
2020-01-29      0.0  3875200   85043200   448200    52900  10518500   5113700
...             ...      ...        ...      ...      ...       ...       ...
2023-11-01      0.0  1996100  109016500  2173700    14800  24089900  17359500
2023-11-08      0.0  3491000  104665800  3526900    27600  28439000  27543200
2023-11-15      0.0  2750600  115033000  1738700     8200  14497100  21869000
2023-11-22      0.0  2350800  117903900  2219700     9400  15925100  17606400
2023-11-29      0.0  2516400  121439000  2635800    11500  20402800  18604700


           AMAR3.SA  RAIL3.SA
Date
2020-01-01  1368838  64703500
2020-01-08  2409912  47155500
2020-01-15  4224594  46031500
2020-01-22  3196288  32542500
2020-01-29  2575631  37268900
...             ...       ...
2023-11-01  3878400  63443800
2023-11-08  7497600  79694500
2023-11-15  6176500  65801700
2023-11-22  3828500  61250000
2023-11-29  5922200  65074000

[205 rows x 56 columns]